### ISSUE TITLE
Use S3 fuse docker image to mount S3 bucket and run API without downloading data

### ISSUE THREAD

**Issue by patrick-zippenfenig** [open-meteo/open-data#1]
It would be interesting to test if the S3fs client could be used to dynamically get weather data. E.g. based on https://github.com/efrecon/docker-s3fs-client

The Open-Meteo S3 open-data bucket would be mounted as a fuse file system can could be used by the API process directly. As latency could severely impact performance, the Docker image should run in AWS us-west-2.

Initial testing:

```yaml
version: '3.8'

services:
  open-meteo-api:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-api
    ports:
      - "80:8080"
    # all options: https://github.com/s3fs-fuse/s3fs-fuse/wiki/Fuse-Over-Amazon
    # debug: -o dbglevel=info -o curldbg
    user: root:root
    entrypoint: /bin/sh -c "apt update && apt install -yy s3fs && mkdir -p /opt/s3fs/bucket && s3fs -o public_bucket=1 openmeteo /opt/s3fs/bucket -o ro -o endpoint=us-west-2 -o use_cache=/opt/cache -o stat_cache_expire=300 && /app/openmeteo-api serve"
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - "apparmor:unconfined"
    restart: always
    volumes:
      - 'cache:/opt/cache'
    environment:
      DATA_DIRECTORY: /opt/s3fs/bucket/data/

volumes:
  cache:
```
